use_frameworks!

target 'FlexUI_Example' do
  platform :ios, '11.0'
  pod 'FlexUI', :path => '../'
  pod 'MagazineLayout'
  pod 'RxSwift'
  pod 'RxCocoa'

#target 'FlexUI_Tests' do
#inherit! :search_paths
#end
end
